openapi: 3.0.3
info:
  title: Kitchen API
  description: API that allows to manage the production of orders in the kitchen.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: URL for local development and testing
  - url: https://coffeemesh.com
    description: main production server
  - url: https://coffeemesh-staging.com
    description: staging server for testing purposes only 
paths:
  /kitchen/schedules:
    get:
      summary: Returns a list of orders scheduled for production
      parameters:
        - name: progress
          in: query
          description: >-
            Whether the order is in progress or not.
            In progress means it's in production in the kitchen.
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: since
          in: query
          required: false
          schema:
            type: string
            format: 'date-time'
      responses:
        '200':
          description: A list of scheduled orders
          content:
            application/json:
              schema:
                additionalProperties: false
                type: object
                properties:
                  schedules: 
                    type: array
                    items:
                      $ref: '#/components/schemas/GetScheduledOrderSchema'
components:
  schemas:
    OrderItemSchema: 
      additionalProperties: false
      type: object
      required:
        - product 
        - quantity
        - size 
      properties:
        product:
          type: string
        size:
          type: string
          enum:
            - small
            - medium
            - big
        quantity:
          type: integer
          minimum: 1

    GetScheduledOrderSchema:
      type: object
      additionalProperties: false
      required:
        - id 
        - order
        - scheduled 
        - status 
      properties:
        id:
          type: string 
          format: uuid
        scheduled: 
          type: string 
          format: 'date-time'
        status:
          type: string
          enum:
            - pending
            - progress 
            - cancelled
            - finished
        order: 
          type: array 
          items: 
            $ref: '#/components/schemas/OrderItemSchema'
